-- SQLite
CREATE TABLE IF NOT EXISTS Train (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid VARCHAR(36) NOT NULL,
    name VARCHAR(30) NOT NULL,
    track VARCHAR(10) NOT NULL,
    wagon VARCHAR(30) NOT NULL,
    date VARCHAR(30) NOT NULL,
    hour VARCHAR(5) NOT NULL,
    freight VARCHAR(16) NOT NULL
)