server:
  http_listen_port: 9080  #Promtail listen port
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://IP:PORT/loki/api/v1/push  #Loki target instance

scrape_configs: #La partie la plus importante
  - job_name: system
    static_configs:
      - targets:
          - localhost #La cible de Promtail est localhost
        labels:
          instance: LogsSSH_VmPA #Identifiant d'étiquette pour l'instance (hostname -f)
          env: ssh #Étiquette d'environnement
          job: secure #Étiquette de tâche
          __path__: /var/log/auth.log